/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap2;

import baitap2.controller.HoaDonController;
import baitap2.controller.NhanVienController;
import baitap2.controller.SanPhamController;
import baitap2.model.NhanVien;
import baitap2.model.SanPham;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duong nhung
 */
public class BaiTap2 extends javax.swing.JFrame {

    /**
     * Creates new form BaiTap2
     */
    CreateTable cr = new CreateTable();

    public BaiTap2() {
        initComponents();
        cr.createTable();
        
        setTableView();
        
        hienThiSuKien(nhanVienController.hienThiNhanVien());
        hienThiSanPham(sanPhamController.hienThiSanPham());
        hienThiHoaDon(hoaDonController.hienThiHoaDon());
    }
    DefaultTableModel tableModelNV = new DefaultTableModel();
    DefaultTableModel tableModelSP = new DefaultTableModel();
    DefaultTableModel tableModelHD = new DefaultTableModel();
    
    NhanVienController nhanVienController = new NhanVienController();
    SanPhamController sanPhamController = new SanPhamController();
    HoaDonController hoaDonController = new HoaDonController();
    
    public void setTableView() {
        String[] titleNV = {"Mã NV", "Họ tên", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Giới tính"};
        tableModelNV.setColumnIdentifiers(titleNV);
        tblNhanVien.setModel(tableModelNV);
        
        String[] titleSP = {"Mã SP", "Tên SP", "Đơn vị tính", "Giá"};
        tableModelSP.setColumnIdentifiers(titleSP);
        tblSanPham.setModel(tableModelSP);
        
        String[] titleHD = {"Mã HĐ", "Mã NV", "Loại HĐ", "Ngày lập","Ngày giao"};
        tableModelHD.setColumnIdentifiers(titleSP);
        tblHoaDon.setModel(tableModelHD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtDvTinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnXoaNV = new javax.swing.JButton();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnThemSP = new javax.swing.JButton();
        btnSuaSP = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNgayGiao = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        txtLoaiHD = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnThemHD = new javax.swing.JButton();
        btnSuaHD = new javax.swing.JButton();
        btnXoaHD = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtSoDT = new javax.swing.JTextField();
        txtMaNV_HD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bảng sản phẩm");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel2.setText("Mã NV");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Họ tên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Ngày sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("Địa chỉ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setText("Giới tính");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 30));
        getContentPane().add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, 30));
        getContentPane().add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, 30));
        getContentPane().add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 30));

        buttonGroup1.add(rbNam);
        rbNam.setSelected(true);
        rbNam.setText("Nam");
        getContentPane().add(rbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        buttonGroup1.add(rbNu);
        rbNu.setText("Nữ");
        getContentPane().add(rbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel7.setText("Sản phẩm");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel8.setText("Mã sản phẩm");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel9.setText("Tên sản phẩm");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel10.setText("Đơn vị tính");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel11.setText("Giá");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 150, 30));
        getContentPane().add(txtMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 150, 30));
        getContentPane().add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 150, 30));
        getContentPane().add(txtDvTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 150, 30));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 660, 180));

        jLabel13.setText("Nhân viên");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, 20));

        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, 20));

        btnSuaNV.setText("Sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, 500, 270));

        btnThemSP.setText("Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        btnSuaSP.setText("Sửa");
        getContentPane().add(btnSuaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, -1));

        btnXoaSP.setText("Xóa");
        getContentPane().add(btnXoaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        jLabel14.setText("Bảng nhân viên");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 10));

        jLabel15.setText("Bảng hóa đơn");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jLabel16.setText("Hóa đơn");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        jLabel17.setText("Mã hóa đơn");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel18.setText("Mã nhân viên");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        jLabel19.setText("Loại hóa đơn");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        jLabel20.setText("Ngày giao nhận");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));
        getContentPane().add(txtNgayGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 690, 160, 30));
        getContentPane().add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 160, 30));
        getContentPane().add(txtLoaiHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 160, 30));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblHoaDon);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 660, 180));

        btnThemHD.setText("Thêm");
        getContentPane().add(btnThemHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));

        btnSuaHD.setText("Sửa");
        getContentPane().add(btnSuaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        btnXoaHD.setText("Xóa");
        getContentPane().add(btnXoaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, -1, -1));

        jLabel21.setText("Ngày lập hóa đơn");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, -1));
        getContentPane().add(txtNgayLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 160, 30));

        jLabel22.setText("Bảng chi tiết hóa đơn");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, -1, -1));

        jLabel23.setText("Mã sản phẩm");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, -1, -1));

        jLabel24.setText("Mã hóa đơn");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 100, -1, -1));

        jLabel26.setText("Đơn giá");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, -1, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, 150, 20));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 150, 20));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 100, 150, 20));

        jLabel27.setText("Số lượng");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 140, -1, -1));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 140, 150, 20));

        jButton10.setText("Thêm");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 70, -1, 20));

        jButton11.setText("Sửa");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 110, -1, 20));

        jButton12.setText("Xóa");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 160, -1, 20));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblNhanVien);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 660, 190));

        jLabel25.setText("Chi tiết hóa đơn");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, -1, -1));

        jLabel28.setText("Số đt");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(txtSoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));
        getContentPane().add(txtMaNV_HD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiSuKien(ResultSet result) {
        try {
            ResultSet res = result;
            tableModelNV.setRowCount(0);
            while (res.next()) {
                String[] row = new String[6];
                row[0] = res.getString("MaNV");
                row[1] = res.getString("HoTen");
                row[2] = res.getString("NgaySinh");
                row[3] = res.getString("DiaChi");
                row[4] = res.getString("SoDT");
                row[5] = res.getString("GioiTinh");
                
                tableModelNV.addRow(row);
            }
            tableModelNV.fireTableDataChanged();
            res.close();
        } catch (Exception e) {
            
        }
    }
    
    public void hienThiSanPham(ResultSet result) {
        try {
            ResultSet res = result;
            tableModelSP.setRowCount(0);
            while (res.next()) {
                String[] row = new String[4];
                row[0] = res.getString("MaSP");
                row[1] = res.getString("TenSP");
                row[2] = res.getString("DonViTinh");
                row[3] = res.getString("Gia");
                tableModelSP.addRow(row);
            }
            tableModelSP.fireTableDataChanged();
            res.close();
        } catch (Exception e) {
            
        }
    }
    
    public void hienThiHoaDon(ResultSet result) {
        try {
            ResultSet res = result;
            tableModelHD.setRowCount(0);
            while (res.next()) {
                String[] row = new String[5];
                row[0] = res.getString("MaHD");
                row[1] = res.getString("TenNV");
                row[2] = res.getString("LoaiHD");
                row[3] = res.getString("NgayLap");
                row[4] = res.getString("NgayGiao");
                tableModelHD.addRow(row);
            }
            tableModelHD.fireTableDataChanged();
            res.close();
        } catch (Exception e) {
            
        }
    }
    
    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        try {
            String maNV = txtMaNV.getText().toString();
            String hoTen = txtHoTen.getText().toString();
            String ngaySinh = txtNgaySinh.getText().toString();
            String diaChi = txtDiaChi.getText().toString();
            String soDT = txtSoDT.getText().toString();
            String gioiTinh = rbNam.isSelected() == true ? "Nam" : "Nữ";
            NhanVien nv = new NhanVien(maNV, hoTen, ngaySinh, diaChi, soDT, gioiTinh);
            nhanVienController.themNhanVien(nv);
            
            hienThiSuKien(nhanVienController.hienThiNhanVien());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnThemNVActionPerformed
    int nvSelected = -1;
    int spSelected = -1;
    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        nvSelected = tblNhanVien.getSelectedRow();
        try {
            String maNV = tblNhanVien.getValueAt(nvSelected, 0).toString();
            NhanVien nv = nhanVienController.timKiemNhanVien(maNV);
            
            txtMaNV.setText(nv.getMaNV());
            txtHoTen.setText(nv.getHoTen());
            txtNgaySinh.setText(nv.getNgaySinh());
            txtDiaChi.setText(nv.getDiaChi());
            txtSoDT.setText(nv.getSoDT());
            
            rbNam.setSelected(nv.getGioiTinh().equals("Nam") ? true : false);
            rbNu.setSelected(!nv.getGioiTinh().equals("Nam") ? true : false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        try {
            String maNV = txtMaNV.getText().toString();
            String hoTen = txtHoTen.getText().toString();
            String ngaySinh = txtNgaySinh.getText().toString();
            String diaChi = txtDiaChi.getText().toString();
            String soDT = txtSoDT.getText().toString();
            String gioiTinh = rbNam.isSelected() == true ? "Nam" : "Nữ";
            NhanVien nv = new NhanVien(maNV, hoTen, ngaySinh, diaChi, soDT, gioiTinh);
            nhanVienController.suaThongTinNhanVien(nv);
            hienThiSuKien(nhanVienController.hienThiNhanVien());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        try {
            nhanVienController.xoaNhanVien(txtMaNV.getText().toString());
            hienThiSuKien(nhanVienController.hienThiNhanVien());
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        try {
            String maSP = txtMaSP.getText().toString();
            String tenSP = txtTenSP.getText().toString();
            String dvTinh = txtDvTinh.getText().toString();
            String gia = txtGia.getText().toString();
            
            SanPham sp = new SanPham(maSP, tenSP, dvTinh, gia);
            sanPhamController.themSanPham(sp);
            
            hienThiSanPham(sanPhamController.hienThiSanPham());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnThemSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiTap2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiTap2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiTap2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiTap2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiTap2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaHD;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnSuaSP;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnXoaHD;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDvTinh;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLoaiHD;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaNV_HD;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNgayGiao;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables
}
